parameters:
  ElasticAPM\Bundle\ElasticAPMBundle\EventListener\ConsoleListener.class: 'ElasticAPM\Bundle\ElasticAPMBundle\EventListener\ConsoleListener'
  ElasticAPM\Bundle\ElasticAPMBundle\EventListener\KernelListener.class: 'ElasticAPM\Bundle\ElasticAPMBundle\EventListener\KernelListener'
  ElasticAPM\Component\Tracker\ApmAgent.class: 'ElasticAPM\Component\Tracker\ApmAgent'
  elastic-apm:
    appName: 'elastic-apm-test'
    listener:
      rules:
        exceptions: true
        requests: true
        commands: true

services:
  PhilKra\Agent:
    class: 'PhilKra\Agent'
    arguments:
      - appName: '%elastic-apm.appName%'
        secretToken: null
        serverUrl: 'http://127.0.0.1:8200'

  ElasticAPM\Component\Tracker\ApmAgent:
    class: 'ElasticAPM\Component\Tracker\ApmAgent.class'
    arguments: ['@PhilKra\Agent']

  ElasticAPM\Bundle\ElasticAPMBundle\EventListener\KernelListener:
    class: '%ElasticAPM\Bundle\ElasticAPMBundle\EventListener\KernelListener.class%'
    arguments: ['@kernel', '@ElasticAPM\Component\Tracker\ApmAgent', '%elastic-apm.listener.rules%']
    tags:
      -  name: 'kernel.event_listener'
         event: 'kernel.exception'
         method: 'onKernelException'
         priority: 0
      -  name: 'kernel.event_listener'
         event: 'kernel.request'
         method: 'onKernelRequest'
         priority: 0
      -  name: 'kernel.event_listener'
         event: 'kernel.terminate'
         method: 'onKernelTerminate'
         priority: 0

  ElasticAPM\Bundle\ElasticAPMBundle\EventListener\ConsoleListener:
    class: '%ElasticAPM\Bundle\ElasticAPMBundle\EventListener\ConsoleListener.class%'
    arguments: ['@kernel', '@ElasticAPM\Component\Tracker\ApmAgent', '%elastic-apm.listener.rules%']
    tags:
      -  name: 'kernel.event_listener'
         event: 'console.command'
         method: 'onConsoleCommand'
         priority: 0
      -  name: 'kernel.event_listener'
         event: 'console.exception'
         method: 'onConsoleException'
         priority: 0
      -  name: 'kernel.event_listener'
         event: 'console.terminate'
         method: 'onConsoleTerminate'
         priority: 0